// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/ee881e7d74e267fca5975d62cb7e6befb6a91014/autobind-decorator/autobind-decorator.d.ts
declare module 'autobind-decorator' {
    function autobind<TFunction extends Function>(target: TFunction): TFunction | void;
    function autobind<T extends Function>(target: Object, propertyKey: string | symbol, descriptor: TypedPropertyDescriptor<T>): TypedPropertyDescriptor<T> | void;
    export = autobind;
}
